"""A collection of manual tests
"""
from time import sleep

from app.llm_classifier import classify_text
from app.stylometrics import analyze

# The following pieces of text were generated by ChatGPT (GPT-5.5)
# Sonnet
ai_generated1 = """
When silver rain has washed the weary stone,
The waking earth exhales a gentle sigh.
Each leaf reflects a world once dim, now shown,
As clouds retreat and swallows learn the sky.

A humble seed beneath the softened ground
Keeps patient faith through darkness, cold, and time.
It does not seek the loudest, grandest sound,
But rises slowly in a silent climb.

So may the heart, though burdened by the years,
Find steady light where hurried eyes see none.
Let hope take root beyond remembered fears,
And bloom beneath the kindness of the sun.

For every storm that bids the daylight cease,
Leaves in its wake the quiet gift of peace.
"""

# Short story excerpt
ai_generated2 = """Every morning I wake up ten minutes before my human’s alarm because someone in this house has to keep the schedule. I stretch one paw at a time, yawn with appropriate drama, and walk across the bed to inspect whether they’re still alive. They usually make a strange grumbling noise when I step on their chest, but moments later they thank me by filling my breakfast bowl. I accept their gratitude with quiet dignity, even though they never seem to appreciate how much work goes into supervising a household.

Once breakfast is complete, I begin my rounds. The windows must be inspected for birds, the hallway rug must be tested for optimal napping conditions, and every cardboard box must be evaluated for structural integrity by sitting inside it. Around midday I patrol the kitchen in case cheese, chicken, or any other valuable resources accidentally fall to the floor. My human calls this “begging.” I call it emergency response.

By evening the sun paints warm squares across the living room floor, and I settle into my favorite one as though I personally arranged the light. My human sits nearby with a book, occasionally reaching over to scratch behind my ears. I pretend not to care for at least a few seconds before leaning into their hand with an involuntary purr. It’s important to maintain professional standards, after all. Running a home is exhausting work, but someone has to do it, and fortunately for this family, they have me."""

# Blog post
ai_generated3 = """
Why Strength Training Is for Everyone

When many people think about strength training, they picture heavy weights and bodybuilders. In reality, strength training is one of the best ways to improve your overall health, no matter your age or fitness level.

Building strength helps make everyday activities easier, from carrying groceries to climbing stairs or playing with your kids. It also supports healthy joints, improves balance, boosts metabolism, and can even help reduce the risk of injuries. The goal isn’t to become the strongest person in the room—it’s to become a stronger, healthier version of yourself.

At our family gym, we believe strength training should be welcoming and accessible to everyone. Whether you’re picking up a dumbbell for the first time or getting back into a routine after a break, we’re here to help you learn proper technique and build confidence at your own pace.

Remember, progress doesn’t happen overnight. Small, consistent efforts add up over time. Every workout is a step toward feeling stronger, moving better, and living a healthier life. We look forward to helping you on that journey.
"""

# Example from CodePath
ai_generated4 = """Artificial intelligence represents a transformative paradigm shift in modern society. 
It is important to note that while the benefits of AI are numerous, it is equally 
essential to consider the ethical implications. Furthermore, stakeholders across 
various sectors must collaborate to ensure responsible deployment."""

# The following pieces of text were sourced online
# Poem, source: https://www.poetryfoundation.org/poetrymagazine/poems/1795751/bella-notte
human_generated1 = """
It’s like the smell of snow
charging through the farms around the island.
Leghorn eggs & aquaculture,
other warm commodities. At night
I slenderized into a gondola
& toured the bleary couple through the city.
The casual canalside restaurants
make us in the mornings
something new & beautiful to eat.
An omelette in the middle of the street?
Not if the pavement
spanked with cherry petals is impassable
& freed of direction.
The lagoon, rocketing with fish,
only a thing entangled in its phrasing.
I am a freight of other boats.
The opposite of traffic, an indifference.
Before we met I was a gondola.
I bid the body bye-bye.
Grab me by the prow & yank me up.
"""

# Short story excerpt, source: https://reedsy.com/short-story/3lmyqb/
human_generated2 = """You should see her. Hunched over her desk, neglecting her children, neglecting her house, and for what? What convinced her that she, of all people, could do this?
The woman is exhausted. Creeping closer to middle age, children, health issues, chronic stress, and do not get me started on the perimenopause. Oof. Reason after reason why she will fail. For one, where will the time and energy come from? It’s not likely she has a spare supply tucked away under the stairs. For another, she has tried this before. Guess where that got her? Nowhere to brag about.
When I bring this up, she desperately grasps at crumbs from her past: the magazine articles (for a now-defunct publication that nobody has heard of), the podcasts, the positive reactions to anything she posted on Facebook. I feel obligated to point out that they were all family and friends. Well, mostly. Of course they were positive.
Yeah, okay. So, she’s not completely inept. But that was years ago, and honestly, nothing to write home about. She didn’t make a single dime, and still, nobody knows who she is. Does that stop her? Unfortunately, not.
Last year, she made submissions to writing contests. Putting her work out there for actual strangers to see and…judge. I tried to stop her. She didn’t win. Not even an acknowledgment. But she was proud of herself regardless. Proud of what?
It gets worse. Somehow.
Now she has the unfettered audacity to think she can write a novel. Not just think it, mind you. She has actually started writing one. Of all the ludicrous, delusional, and harebrained ideas. I swear, this perimenopause thing has disintegrated any remaining shred of sanity she had left.
"""

# Blog post, source: https://www.jtsstrength.com/considerations-for-masters-lifters/
human_generated3 = """Considerations for Masters Lifters
Typically, Masters divisions for Powerlifting begin at 40 years old. Here are some important things to consider about training as you age.

Considerations for Masters Lifters:

✅Training History/Athletic Background
We all age differently based on our genetics, athletic background, and training history. Look at the lifter’s past and strategically develop a yearly plan that will best suit the athlete and their goals.

✅ Injury History
Because a masters lifter can have an extensive background in other sports you need to take into consideration any previous injury that can affect programming and adjust things like exercise selection, volume, and periodization.

✅ What Stage of Their Career Are They In
As athletes age both in number and in their training age, programming will need to reflect this. Strategically selecting meets, prioritizing recovery, and proper exercise selection are all things to consider.

✅ Fatigue Management
We want to reduce joint stress, especially for the older lifter. This is done by exercise selection that will help improve the quality of movement while not overloading the athlete with too much volume or work.
"""

# Example from CodePath
human_generated4 = """ok so i finally tried that new ramen place downtown and honestly? 
underwhelming. the broth was fine but they put WAY too much sodium in it and 
i was thirsty for like three hours after. my friend got the spicy version and 
said it was better. probably won't go back unless someone drags me there"""

if __name__ == '__main__':
    ai_text = [ai_generated1, ai_generated2, ai_generated3, ai_generated4]
    human_text = [human_generated1, human_generated2, human_generated3, human_generated4]

    print('Performing evaluations on AI written text:')
    for ai in ai_text:
        print(f"{ai=:.30}")
        ai_eval = classify_text(ai)
        stylo_eval = analyze(ai)
        print(f"AI Evaluation: {ai_eval}\nStylometrics Evaluation: {stylo_eval}")
        print('-'*50)
        sleep(3)

    print('Performing evaluations on human written text:')
    for human in human_text:
        print(f"{human=:.30}")
        ai_eval = classify_text(human)
        stylo_eval = analyze(human)
        print(f"AI Evaluation: {ai_eval}\nStylometrics Evaluation: {stylo_eval}")
        print('-'*50)
        sleep(3)