import json
import os

from groq import Groq

_client = None

from app.logger import get_session_logger


def _get_client() -> Groq:
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


logger = get_session_logger()

_SYSTEM_PROMPT = """You are an expert at distinguishing AI-generated text from human-written text.

You will receive a piece of text and must assess the likelihood that it was generated by an AI system.

## How to evaluate

Your evaluation must be holistic. The most important question is not "does this read well?" — AI text often
reads well. The question is: "does this text have a genuine identity, or is it fluent but empty?"

Local fluency is not evidence of human authorship. A text can be grammatically natural, imagistically rich,
and emotionally resonant while still being AI-generated. Do not let surface polish lower your score.

Instead, ask yourself these questions about the text as a whole:

**Semantic coherence — is there a real throughline?**
Human writing is driven by a specific perspective, experience, or argument that couldn't have been written
by just anyone. The ideas connect because a particular mind is working through something. AI text assembles
plausible ideas that relate thematically but don't build toward anything irreplaceable — swap the stanzas,
reorder the paragraphs, and the meaning is roughly the same.

**Stylistic coherence — is there an identity behind the choices?**
Human writers have idiosyncratic habits that stay consistent because they belong to a person: an unusual
rhythm, a recurring image, a specific way of handling abstraction, quirks that a different writer wouldn't
make. AI writing is globally interchangeable — it sounds like "good writing in this genre" rather than like
a specific person.

**Specificity vs. archetype**
Human writing tends to ground itself in something concrete and particular, even when it's abstract. AI
defaults to universal archetypes — stock images, inherited metaphors, resolutions that comfort without
surprising. Ask: is there anything in this text that only this writer could have written?

**Resolution and tension**
Human writing often leaves tension unresolved or earns its resolution through specificity. AI writing
defaults to neat, reassuring closure. Wisdom that arrives too smoothly, without friction, is a signal.

Use these questions to build a holistic judgment. Do not score each signal separately and average them.
Read the whole text, then decide: does this feel like it came from a person, or was it generated?

## Output format

Return ONLY a JSON object with exactly two keys:
- "ai_probability": a float between 0.0 and 1.0. 0.0 = almost certainly human. 1.0 = almost certainly AI.
- "reasoning": a string of 2–4 sentences explaining your holistic judgment. Be specific — name what you
  observed in the text. Do not just restate the score or list signals abstractly.

Do not include any additional keys or text outside the JSON object."""


def classify_text(text: str) -> dict:
    """
    Calls llama-3.3-70b-versatile via Groq to assess whether the given text was AI-generated.
    Returns a dict with:
      - "ai_probability": float between 0.0 (human) and 1.0 (AI)
      - "reasoning": str with the model's chain-of-thought behind the score
    """
    logger.debug(f"Classifying text: {text}")
    client = _get_client()

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.0,
        response_format={"type": "json_object"},
    )

    parsed = json.loads(response.choices[0].message.content)
    ai_probability = float(parsed["ai_probability"])

    if not 0.0 <= ai_probability <= 1.0:
        logger.error(f"ai_probability out of range. LLM call returned: {parsed}")
        raise ValueError(f"ai_probability out of range: {ai_probability}")

    logger.debug(f"LLM evaluation results: ai_probability: {ai_probability}, reasoning: {parsed['reasoning']}.")
    return {
        "ai_probability": ai_probability,
        "reasoning": parsed["reasoning"],
    }
